name: "Delete Blacksmith Cache"
author: Aayush Shah
description: "Deletes a cache or specific cache version from Blacksmith"
branding:
  icon: folder-plus
  color: black
inputs:
  key:
    description: "The cache key to delete"
    required: true
  version:
    description: "Specific version of the cache to delete (optional)"
    required: false
runs:
  using: "node20"
  main: "dist/index.js"
