name: "Blacksmith Sticky Disk"
author: Aditya Maru
description: "Creates a sticky disk on Blacksmith"
branding:
  icon: folder-plus
  color: black
inputs:
  key:
    description: "A unique key to identify the sticky disk"
    required: true
  path:
    description: "The path at which to mount the sticky disk"
    required: true
runs:
  using: "node20"
  main: "dist/index.js"
  post: "dist/post/index.js"
